name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load .env file
      run: |
        if [ -f .env ]; then
          export $(cat .env | xargs)
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: jdk
        architecture: x64
        check-latest: false

    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONARQUBE_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      run: |
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ env.SONARQUBE_HOST_URL }} \
          -Dsonar.login=${{ env.SONAR_TOKEN }}

    - name: Upload SonarQube analysis results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: sonar-analysis-results
        path: build/sonar-report.json
